version: '2'
services:
    fpla-app:
        image: fpla
        external_links:
            - fpla-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/fpla
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fpla-postgresql:
        extends:
            file: postgresql.yml
            service: fpla-postgresql
