version: '2'
services:
    fpla-postgresql:
        container_name: fpla-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/fpla/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=fpla
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
